### ISSUE TITLE
Doesn't respond if I first tap in the center and then drag

### ISSUE THREAD

**Issue by kuprel** [tichise/OMJoystick#5]
Cool joystick.  I tried it out on iOS 14 and it only responds if I initially tap outside the center.  Is there an easy way to fix this?

**Comment by RobertHalwass** [comment]
I am having problems with this. When I touch the center of the small circle directly it doesn't move. Only when I touch the outer edge of the small circle it moves to where I touch and then I can control it as expected. This makes it hard to get values under ~30. Aside from that, it's great.
I use 0.6.2 installed via Swift Package Manager on an iPad Pro 2020 and iPhone 11 both running iOS 14.4.
